### ISSUE TITLE
Plug-ins blocks Enter key in Editor

### ISSUE THREAD

**Issue by kborghs** [alirezamirian/Angular-Templates#2]
When pressing the Enter-key in the editor, nothing happens.

In idea.log, I get the following stacktrace:

```
2016-01-04 13:13:15,343 [ 121613]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 15.0.2  Build #IU-143.1184.17 
2016-01-04 13:13:15,343 [ 121613]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.7.0_71 
2016-01-04 13:13:15,343 [ 121613]  ERROR - llij.ide.plugins.PluginManager - VM: Java HotSpot(TM) 64-Bit Server VM 
2016-01-04 13:13:15,343 [ 121613]  ERROR - llij.ide.plugins.PluginManager - Vendor: Oracle Corporation 
2016-01-04 13:13:15,344 [ 121614]  ERROR - llij.ide.plugins.PluginManager - OS: Windows 7 
2016-01-04 13:13:15,344 [ 121614]  ERROR - llij.ide.plugins.PluginManager - Last Action: ShowLog 
2016-01-04 13:13:15,486 [ 121756]  ERROR - llij.ide.plugins.PluginManager - null 
java.lang.NullPointerException
    at com.intellij.openapi.editor.actionSystem.EditorAction.update(EditorAction.java:118)
    at com.intellij.openapi.editor.actionSystem.EditorAction.updateForKeyboardAccess(EditorAction.java:122)
    at com.intellij.openapi.editor.actionSystem.EditorAction.update(EditorAction.java:135)
    at com.intellij.openapi.actionSystem.AnAction.beforeActionPerformedUpdate(AnAction.java:246)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:111)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:622)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.c(IdeKeyEventDispatcher.java:485)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:215)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:622)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by alirezamirian** [comment]
Thanks for reporting.
The two things that I'm suspected of, are JDK and IDEA versions. I'm gonna debug on both java 7 and IDEA 15 separately to see if the bug is somehow related to them. 
BTW, do you have AngularJS plugin installed on your IDE?

**Comment by kborghs** [comment]
I have installed:
- AngularJS plugin
- ScaffAngular plugin (I will try to disable it, because I don't use it anyway)
- IntelliJ IDEA 15.0.2
- Java 1.7.0_71

**Comment by kborghs** [comment]
I now tried it without ScaffAngular.The same issue occurs.

**Comment by notbear** [comment]
Hi,

I'm getting the same problem in WebStorm 11. Stacktrace:

```
2016-02-05 23:28:08,787 [   8703]  ERROR - nsions.impl.ExtensionPointImpl - WebStorm 11.0.3  Build #WS-143.1559.5 
2016-02-05 23:28:08,787 [   8703]  ERROR - nsions.impl.ExtensionPointImpl - JDK: 1.7.0_80 
2016-02-05 23:28:08,787 [   8703]  ERROR - nsions.impl.ExtensionPointImpl - VM: Java HotSpot(TM) 64-Bit Server VM 
2016-02-05 23:28:08,787 [   8703]  ERROR - nsions.impl.ExtensionPointImpl - Vendor: Oracle Corporation 
2016-02-05 23:28:08,788 [   8704]  ERROR - nsions.impl.ExtensionPointImpl - OS: Linux 
2016-02-05 23:28:08,788 [   8704]  ERROR - nsions.impl.ExtensionPointImpl - Last Action:  
2016-02-05 23:28:08,839 [   8755]  ERROR - nsions.impl.ExtensionPointImpl - com/hasintech/intellij/angularTemplates/AngularLiveTemplateProvider : Unsupported major.minor version 52.0 [Plugin: com.hasintech.intellij.angularTemplates] 
com.intellij.openapi.extensions.impl.PicoPluginExtensionInitializationException: com/hasintech/intellij/angularTemplates/AngularLiveTemplateProvider : Unsupported major.minor version 52.0 [Plugin: com.hasintech.intellij.angularTemplates]
    at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentInstance(ExtensionComponentAdapter.java:96)
    at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getExtension(ExtensionComponentAdapter.java:119)
    at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:249)
    at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:194)
    at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:100)
    at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:87)
    at com.intellij.openapi.extensions.ExtensionPointName.getExtensions(ExtensionPointName.java:49)
    at com.intellij.codeInsight.template.impl.TemplateSettings.a(TemplateSettings.java:429)
    at com.intellij.codeInsight.template.impl.TemplateSettings.<init>(TemplateSettings.java:248)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
    at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
    at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
    at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
    at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:59)
    at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:232)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:212)
    at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:46)
    at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:37)
    at com.intellij.codeInsight.template.impl.TemplateSettings.getInstance(TemplateSettings.java:252)
    at com.intellij.codeInsight.template.impl.TemplateSearchableOptionContributor.processOptions(TemplateSearchableOptionContributor.java:34)
    at com.intellij.ide.ui.search.SearchableOptionsRegistrarImpl$3.run(SearchableOptionsRegistrarImpl.java:122)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
Caused by: com.intellij.diagnostic.PluginException: com/hasintech/intellij/angularTemplates/AngularLiveTemplateProvider : Unsupported major.minor version 52.0 [Plugin: com.hasintech.intellij.angularTemplates]
    at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:130)
    at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:278)
    at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.loadImplementationClass(ExtensionComponentAdapter.java:157)
    at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentImplementation(ExtensionComponentAdapter.java:66)
    at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentInstance(ExtensionComponentAdapter.java:73)
    ... 32 more
Caused by: java.lang.UnsupportedClassVersionError: com/hasintech/intellij/angularTemplates/AngularLiveTemplateProvider : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:257)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:253)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:222)
    at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:124)
    ... 40 more
Caused by:

com.intellij.diagnostic.PluginException: com/hasintech/intellij/angularTemplates/AngularLiveTemplateProvider : Unsupported major.minor version 52.0 [Plugin: com.hasintech.intellij.angularTemplates]
    at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:130)
    at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:278)
    at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.loadImplementationClass(ExtensionComponentAdapter.java:157)
    at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentImplementation(ExtensionComponentAdapter.java:66)
    at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentInstance(ExtensionComponentAdapter.java:73)
    at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getExtension(ExtensionComponentAdapter.java:119)
    at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:249)
    at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:194)
    at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:100)
    at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:87)
    at com.intellij.openapi.extensions.ExtensionPointName.getExtensions(ExtensionPointName.java:49)
    at com.intellij.codeInsight.template.impl.TemplateSettings.a(TemplateSettings.java:429)
    at com.intellij.codeInsight.template.impl.TemplateSettings.<init>(TemplateSettings.java:248)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
    at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
    at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
    at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
    at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:59)
    at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:232)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:212)
    at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:46)
    at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:37)
    at com.intellij.codeInsight.template.impl.TemplateSettings.getInstance(TemplateSettings.java:252)
    at com.intellij.codeInsight.template.impl.TemplateSearchableOptionContributor.processOptions(TemplateSearchableOptionContributor.java:34)
    at com.intellij.ide.ui.search.SearchableOptionsRegistrarImpl$3.run(SearchableOptionsRegistrarImpl.java:122)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
Caused by: java.lang.UnsupportedClassVersionError: com/hasintech/intellij/angularTemplates/AngularLiveTemplateProvider : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:257)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:253)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:222)
    at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:124)
    ... 40 more
```

**Comment by alirezamirian** [comment]
@notbear 
Actually this seems to be different error based on error log.
It's probably because of the mismatch between java versions in compile and execution. 
I myself saw the module name suggestions not working in Webstorm 11. Is this the case for you too?
I'll try to compile with java 1.7 to see if it fixes the problem.

**Comment by notbear** [comment]
@alirezamirian Yes, the stacktrace look different, but the issue is the same: after installing Angular Templates plugin the Enter/Return key doesn't work in editor.

**Comment by reetu** [comment]
I'm experiencing this issue after upgrading IntelliJ jetbrains to 15.0.6. Any word on a suggested workaround?

**Comment by cwagner22** [comment]
+1
